### ISSUE TITLE
main.ERROR: Please provide payment for the order. [] []

### ISSUE THREAD

**Issue by gondas33** [mobilpay/Magento#35]
At random times, I'm having orders that are stuck in Pending Payment, even if they are paid in MobilPay Dashboard.

I could find two type of errors in system.log:

1. `Deprecated Functionality: md5(): Passing null to parameter #1 ($string) of type string is deprecated in public_html/app/code/Netopia/Netcard/Controller/Payment/Guest.php on line 94`  
-> fixed by adding ?? '' : ` if(md5($order->getCustomerEmail() ?? '') != $code){`

2. ` main.ERROR: Please provide payment for the order. [] []
 main.CRITICAL: Magento\Framework\Exception\LocalizedException: Please provide payment for the order. in public_html/vendor/magento/module-payment/Observer/SalesOrderBeforeSaveObserver.php:29`

in the stacktrace you can find the Redirect.php from Netopia causing this issue:

```
#8 public_html/vendor/magento/framework/Model/AbstractModel.php(658): Magento\Sales\Model\ResourceModel\Order\Interceptor->save()

#9 public_html/app/code/Netopia/Netcard/Controller/Payment/Redirect.php(57): Magento\Framework\Model\AbstractModel->save()

#10 public_html/vendor/magento/framework/Interception/Interceptor.php(58): Netopia\Netcard\Controller\Payment\Redirect->execute()
```

Any clue what is causing the behaviour I mentioned? Pretty sure it's related to the Redirect.php error.

Thank you!

**Comment by navid59** [comment]
Sorry for the late reply. This issue has already been solved by the implementation department
